// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Extracts blood pressure data from an image using OCR.
 *
 * - extractBloodPressureData - A function that extracts blood pressure data from an image.
 * - ExtractBloodPressureDataInput - The input type for the extractBloodPressureData function.
 * - ExtractBloodPressureDataOutput - The return type for the extractBloodPressureData function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractBloodPressureDataInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a blood pressure reading, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ExtractBloodPressureDataInput = z.infer<
  typeof ExtractBloodPressureDataInputSchema
>;

const ExtractBloodPressureDataOutputSchema = z.object({
  date: z.string().describe('The date of the blood pressure reading.'),
  time: z.string().describe('The time of the blood pressure reading.'),
  systolic: z.number().describe('The systolic blood pressure value.'),
  diastolic: z.number().describe('The diastolic blood pressure value.'),
});

export type ExtractBloodPressureDataOutput = z.infer<
  typeof ExtractBloodPressureDataOutputSchema
>;

export async function extractBloodPressureData(
  input: ExtractBloodPressureDataInput
): Promise<ExtractBloodPressureDataOutput> {
  return extractBloodPressureDataFlow(input);
}

const extractBloodPressureDataPrompt = ai.definePrompt({
  name: 'extractBloodPressureDataPrompt',
  input: {schema: ExtractBloodPressureDataInputSchema},
  output: {schema: ExtractBloodPressureDataOutputSchema},
  prompt: `You are an expert OCR reader for blood pressure readings.

  Extract the date, time, systolic, and diastolic values from the image.

  Photo: {{media url=photoDataUri}}`,
});

const extractBloodPressureDataFlow = ai.defineFlow(
  {
    name: 'extractBloodPressureDataFlow',
    inputSchema: ExtractBloodPressureDataInputSchema,
    outputSchema: ExtractBloodPressureDataOutputSchema,
  },
  async input => {
    const {output} = await extractBloodPressureDataPrompt(input);
    return output!;
  }
);
