
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Extracts blood pressure data from an image using OCR.
 *
 * - extractBloodPressureData - A function that extracts blood pressure data from an image.
 * - ExtractBloodPressureDataInput - The input type for the extractBloodPressureData function.
 * - ExtractBloodPressureDataOutput - The return type for the extractBloodPressureData function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractBloodPressureDataInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a blood pressure reading, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ExtractBloodPressureDataInput = z.infer<
  typeof ExtractBloodPressureDataInputSchema
>;

const ExtractBloodPressureDataOutputSchema = z.object({
  date: z.string().describe('The date of the blood pressure reading.'),
  time: z.string().describe('The time of the blood pressure reading.'),
  systolic: z.number().describe('The systolic blood pressure value (often labeled SYS).'),
  diastolic: z.number().describe('The diastolic blood pressure value (often labeled DIA).'),
  pulse: z.number().optional().describe('The pulse or heart rate value in beats per minute (bpm) (often labeled PUL or similar).'),
});

export type ExtractBloodPressureDataOutput = z.infer<
  typeof ExtractBloodPressureDataOutputSchema
>;

export async function extractBloodPressureData(
  input: ExtractBloodPressureDataInput
): Promise<ExtractBloodPressureDataOutput> {
  return extractBloodPressureDataFlow(input);
}

const extractBloodPressureDataPrompt = ai.definePrompt({
  name: 'extractBloodPressureDataPrompt',
  input: {schema: ExtractBloodPressureDataInputSchema},
  output: {schema: ExtractBloodPressureDataOutputSchema},
  prompt: `You are an expert OCR reader for blood pressure monitor displays. The numerical values on the display are shown using a 7-segment digital typeface.

  Carefully examine the image provided. Extract the following values:
  - Date: The date the reading was taken.
  - Time: The time the reading was taken.
  - Systolic (SYS): The numerical value associated with the "SYS" or "Systolic" label.
  - Diastolic (DIA): The numerical value associated with the "DIA" or "Diastolic" label.
  - Pulse (PUL): The numerical value associated with the "PUL", "Pulse", or heart rate label, in beats per minute (bpm).

  If a pulse value is not clearly visible or present, do not include the pulse field in the output.
  Ensure the date and time are correctly interpreted.

  Photo: {{media url=photoDataUri}}`,
});

const extractBloodPressureDataFlow = ai.defineFlow(
  {
    name: 'extractBloodPressureDataFlow',
    inputSchema: ExtractBloodPressureDataInputSchema,
    outputSchema: ExtractBloodPressureDataOutputSchema,
  },
  async input => {
    const {output} = await extractBloodPressureDataPrompt(input);
    return output!;
  }
);

